<a href="https://colab.research.google.com/github/tonpiplaifa/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

14/1/2564

ที่เรียนไปแล้วมี 1 ตัวคือ list หน้าตาประมาณนี้

ข้อดีของ list ใน python ที่ดีกว่า array
- เป็นช่องเก็บที่สามารถเก็บไว้ได้หลายประเภท
- เขียนโค้ดได้ง่ายกว่า เช่น list slidsing


#Dictionary

ปรับเปลี่ยนจาก list ที่สามารถ index หรือชี้ด้วยอะไรก็ได้
สิ่งที่หายไปคือลำดับที่เรียงกัน แต่จะเป็นเหมือน dic เรียงจากตัวอักษร

In [ ]:
ex_dict = {'a':10,'1':1,'stat':5} #curly bracketsในการบอกว่าเป็น dict
#สร้าง dict ใช้ a ชี้ไปที่เวข 10

In [ ]:
ex_dict['stat']#การเรียกสมาชิกใน dict

5

In [ ]:
ex2_dict = {1:'one', 2:'two',3:'three'}

####การเพิ่มสมาชิกใน dict

ไม่สามารถไปต่อหลังได้แบบ list

In [ ]:
ex2_dict[0] = 'zero' #index = 0 เพิ่มสมาชอก zero

In [ ]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}

**คำสั่ง**

In [ ]:
ex2_dict.keys() #สามารถอง index ทั้งหมดว่ามีอะไรบ้าวงจะจะได้เรียกถูก
#keys คือตัวหน้า values คือตัวหลัง

dict_keys([1, 2, 3, 0])

In [ ]:
for index in ex2_dict.keys():
 print(index) #ลำดับจะไม่เรียง

1
2
3
0


In [ ]:
ex2_dict.values() #keys คือตัวหน้า values คือตัวหลัง

dict_values(['one', 'two', 'three', 'zero'])

**ตวามสำคัญของ dict คือ นำไปในจะ dataframe ของ pandas**

#Numpy Array (หรือ array ที่มี n มิติ)

numpy คือ package ที่สามารถเกียวกับ array ของตัวเลข (ที่มีคนเขียนขึ้นมาและนิยมใช้ numpy -> number python)

In [ ]:
import numpy #วิธีที่เรียกใช้งาน package

####สร้าง Numpy Array

In [ ]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


####การชี้ค่าใน numpy array

In [ ]:
ex_2d_array[1,2] #0.3 อยู่แถว 1 หลักที่ 2 เนื่องจากต่างๆเริ่มที่ 0

0.3

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #กรณีชี้ list

In [ ]:
print(len(list_x))
print(list_x[1])
print(list_x[1][2])

2
[9.1, 0.1, 0.3]
0.3


####Operations

In [ ]:
ex2_2d_array = numpy.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array) #array ทั้งสองที่แถวและหลักเท่ากัน

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array.shape #ตรวจสอบขนาดของ matrix

(2, 3)

In [ ]:
ex_2d_array + ex2_2d_array #ตำแหน่งเดียวกันบวกกัน

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]

list_x + list_x2 #เป็นการนำสมาชิกมาต่อกัน

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]

In [ ]:
ex_2d_array * ex2_2d_array #การคูณแบบ array คือการเอาตำแหน่งเดียวกันมาคูณกัน

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

**matrix multiplication (การคูณเมทริกซ์จริงๆต้อง .dot)**

In [ ]:
numpy.dot(ex_2d_array,ex2_2d_array.T) #แถวของเมทริกหน้าต้องเท่ากับแถวของตัวหลัง เคสนี้เลยต้องทรานซ์

array([[5.2, 4.5],
       [9.1, 0.3]])

In [ ]:
print(ex2_2d_array)
print(ex2_2d_array.T) #เปลี่ยนแถวเป็นหลัก

[[1 0 0]
 [0 0 1]]
[[1 0]
 [0 0]
 [0 1]]


det จะต้องเป็นเมทริกซ์ที่มีแถวเท่ากับหลัก

In [ ]:
dot_mat = numpy.dot(ex_2d_array,ex2_2d_array.T)
print(dot_mat)

[[5.2 4.5]
 [9.1 0.3]]


In [ ]:
numpy.linalg.det(dot_mat)

-39.389999999999986

สามารถทำ operation อื่นได้อีก สามารถหาดูได้ ที่ error อาจจะเพราะไม่ตรงข้อดำหนดหรือนิยายของมัน

####matrix slicing

In [ ]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array[1,1:] #แถวที่ 1 หลักที่ 1 ถึง 2

array([0.1, 0.3])

In [ ]:
ex_2d_array[:,:2] #ทุกแถว หลักแรกถึง 2

array([[5.2, 3. ],
       [9.1, 0.1]])

#### HW5 
เขียน function คูณ matrix แล้ว test กับ matrix ขนาด


*  (2,3)*(3,2)
*  (4,4)*(,)
*   

---


 


In [ ]:
import numpy as np

In [ ]:
matrix_0 = np.array([[1,2,3],[4,5,6]]) #matrix 2*3
matrix_1 = np.array([[7,8],[9,10],[11,12]]) #matrix 3*2
print(matrix_0)
print(matrix_1)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
matrix_2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]) #matrix 4*4
matrix_3 = np.array([[17],[18],[19],[20]]) #matrix 4*1
print(matrix_2)
print(matrix_3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17]
 [18]
 [19]
 [20]]


In [ ]:
matrix_4 = np.array([[1,2],[3,4]]) #matrix 2*2
matrix_5 = np.array([[5,6],[7,8]]) #matrix 2*2
print(matrix_4)
print(matrix_5)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
def matrix(matrix_0,matrix_1) :
    g = [[0 for row in range(len(matrix_1[0]))] for col in range(len(matrix_1))]
    for i in range(len(matrix_0)) :
        for j in range(len(matrix_1[0])) :
            for k in range(len(matrix_1)) :
                g[i][j] += matrix_0[i][k]*matrix_1[k][j]
    mat_ans = np.matrix(g)
    return mat_ans

In [ ]:
# matrix (2,3)*(3,2)
print(matrix_0)
print(matrix_1)
matrix(matrix_0,matrix_1)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


matrix([[ 58,  64],
        [139, 154],
        [  0,   0]])

In [ ]:
# matrix (4,4)*(4,1)
print(matrix_2)
print(matrix_3)
matrix(matrix_2,matrix_3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17]
 [18]
 [19]
 [20]]


matrix([[ 190],
        [ 486],
        [ 782],
        [1078]])

In [ ]:
# matrix (2,2)*(2,2)
print(matrix_4)
print(matrix_5)
matrix(matrix_4,matrix_5)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


matrix([[19, 22],
        [43, 50]])

In [ ]:
#ตรวจ

In [ ]:
dot_1 = np.dot(matrix_0,matrix_1)
print(dot_1)

[[ 58  64]
 [139 154]]


In [ ]:
dot_2 = np.dot(matrix_2,matrix_3)
print(dot_2)

[[ 190]
 [ 486]
 [ 782]
 [1078]]


In [ ]:
dot_3 = np.dot(matrix_4,matrix_5)
print(dot_3)

[[19 22]
 [43 50]]
